### ISSUE TITLE
n ciphers?

### ISSUE THREAD

**Issue by ghost** [samhoooo/dynamic-QR-code#2]

**Comment by samhoooo** [comment]
This project uses RSA encryption algorithm. What are the other algorithms you would like to implement?

**Comment by samhoooo** [comment]
AES and DES are symmetric encryption algorithms, which I am afraid not applicatable in this QR code application. (it needs to keep the secret key on the server side)

However, asymmetric encryption algorithms such as ECC (Elliptic Curve Cryptography), and DSA (Digital Signature Algorithm) would be interesting to implement. 

What do you think? I would appreciate any idea, or even we can collaborate on a PR.
